Web/SSO.SGP.Web/Areas/Expedientes/Controllers/ProveedoresController.cs
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SSO.SGP.EntidadesDeNegocio;
using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
using SSO.SGP.ReglasDeNegocio;
using SSO.SGP.EntidadesDeNegocio.Vistas;
using System;
using System.Data;
using Syncrosoft.Framework.Utils.Logs;

namespace SSO.SGP.Web.Areas.Expedientes.Controllers
{
	public class ProveedoresController : Controller
	{
        private ProveedoresRN oProveedoresRN = new ProveedoresRN();
		private FormasDePagoRefRN oFormasDePagoRefRN = new FormasDePagoRefRN();
		
		private TiposCuentasBancariasRefRN oTiposCuentasBancariasRefRN = new TiposCuentasBancariasRefRN();
		
		public ActionResult Index()
        {
            return View();
        }

		public ActionResult Default() 
		{
			return View();
		}

        public DataTablesResult<ProveedoresView> getProveedoresGrilla(DataTablesParam dataTableParam)
        {
            return DataTablesResult.Create(this.oProveedoresRN.ObtenerParaGrilla(), dataTableParam, a => new ProveedoresView()
            {	
			Id=a.Id,	
			Nombre=a.Nombre,	
			RazonSocial=a.RazonSocial,	
			DomicilioReal=a.DomicilioReal,	
			CodigoPostal=a.CodigoPostal,	
			CUIT=a.CUIT,	
			IngresosBrutos=a.IngresosBrutos,	
			Estado=a.Estado
            });
        }

		public ActionResult Crear()
        {
			ViewBag.FormasDePagoRef = new SelectList(oFormasDePagoRefRN.ObtenerTodo().ToList(), "Id", "Id");
			ViewBag.TiposCuentasBancariasRef = new SelectList(oTiposCuentasBancariasRefRN.ObtenerTodo().ToList(), "Id", "Id");
            return View();
        }

        [HttpPost]
        public ActionResult Crear(Proveedores proveedores)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    proveedores.FechaAlta = DateTime.Now;
                    proveedores.FechaModifica = DateTime.Now;
                    proveedores.UsuarioAlta = SessionHelper.IdUsuario.Value;
                    proveedores.UsuarioModifica = SessionHelper.IdUsuario.Value;
                    oProveedoresRN.Guardar(proveedores);
                    return Json(new object[] { true, String.Format("Se guardo Proveedores satisfactoriamente") });
                }
                catch (Exception ex)
				{
					Logger.GrabarExcepcion(ex, false);
                    return Json(new object[] { false, "No se ha podido guardar Proveedores" });
                }
            }
            else
            {
                return Json(new object[] { false, "No se ha podido guardar Proveedores" });
            }
        }
	
	
		[HttpPost]
        public ActionResult Editar(Proveedores proveedores)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    oProveedoresRN.Actualizar(proveedores);
                    return Json(new object[] { true, String.Format("Se guardo satisfactoriamente Proveedores") });
                }
                catch (Exception ex)
				{
					Logger.GrabarExcepcion(ex, false);
                    return Json(new object[] { false, "No pudo guardarse Proveedores" });
                }
            }
            else
            {
                return Json(new object[] { false, "No pudo guardarse Proveedores" });
            }

        }

        public ActionResult Editar(int id = 0)
        {
			
			ViewBag.FormasDePagoRef = new SelectList(oFormasDePagoRefRN.ObtenerTodo().ToList(), "Id", "Id");
			
			ViewBag.TiposCuentasBancariasRef = new SelectList(oTiposCuentasBancariasRefRN.ObtenerTodo().ToList(), "Id", "Id");
			
		
            Proveedores proveedores = oProveedoresRN.ObtenerPorId(id);
            if (proveedores == null)
            {
                return HttpNotFound();
            }
            return View(proveedores);
        }
	

        [HttpPost, ActionName("Eliminar")]
        public ActionResult EliminarConfirmado(int id)
        {
            try
            {
                oProveedoresRN.Eliminar(id);
                return Json(new 	object[] { true, "La operación se realizó satisfactoriamente" });
            }
            catch (Exception ex)
			{
				Logger.GrabarExcepcion(ex, false);
                return Json(new object[] { false, "No pudo eliminarse el proveedores" });
            }
        }
		
		public JsonResult JsonT(string term)
        {
            var res = from x in this.oProveedoresRN.JsonT(term)
                      select x;
            return this.Json(res, JsonRequestBehavior.AllowGet);
        }
		
		//--- Utilizar esta acción para Autocomplete
		public JsonResult JsonOptions(string term)
        {
            var res = from x in this.oProveedoresRN.ObtenerOptions(term)
                      select x;
            return this.Json(res, JsonRequestBehavior.AllowGet);
        }

        //--- Utilizar esta acción para Autocomplete
        public JsonResult Autocomplete(string term)
        {
            var res = from x in this.oProveedoresRN.GetAutocomplete(term)
                      select new {label=x.Nombre, id=x.Id, text = x.Nombre, cuit = x.CUIT };
            return this.Json(res, JsonRequestBehavior.AllowGet);
        }
		



	protected override void Dispose(bool disposing)
        {
            oProveedoresRN.Dispose();
			
				oFormasDePagoRefRN.Dispose();
			
				oTiposCuentasBancariasRefRN.Dispose();
			
            base.Dispose(disposing);
        }
	
	} //fin de clase
}

Web/SSO.SGP.Web/Areas/RRHH/Controllers/AgentesController.cs
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SSO.SGP.EntidadesDeNegocio;
using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
using SSO.SGP.ReglasDeNegocio;
using SSO.SGP.EntidadesDeNegocio.Vistas;
using System;
using System.Data;
using Syncrosoft.Framework.Utils.Logs;
using SSO.SGP.EntidadesDeNegocio.Results;
using SSO.SGP.Web.BasicConsumer;
using SSO.SGP.AccesoADatos;
using System.Collections.Generic;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using Manatee.Trello.ManateeJson;
using Manatee.Trello;
using Manatee.Trello.WebApi;
using SSO.SGP.Web.Controllers;
using System.Net;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using System.Globalization;
using DocumentFormat.OpenXml;

namespace SSO.SGP.Web.Areas.RRHH.Controllers
{
    public class AgentesController : Controller
    {
        private AgentesRN oAgentesRN = new AgentesRN();
        private CargosRefRN oCargosRefRN = new CargosRefRN();
        private LocalidadesRefRN oLocalidadesRN = new LocalidadesRefRN();
        private OrganismosRefRN oOrganismosRN = new OrganismosRefRN();
        private ParametrosadmRN oParametrosRN = new ParametrosadmRN();
        private PersonasRN oPersonasRN = new PersonasRN();
        private AgentesAD oAgentes = new AgentesAD();
        private CesidaParametrosDeMovimientosAD oParametrosDeMovimiento = new CesidaParametrosDeMovimientosAD();
        private AgentesBonificacionesAD oBonificaciones = new AgentesBonificacionesAD();
        private CesidaCategoriasAD oCesidaCategorias = new CesidaCategoriasAD();
        private CesidaMovimientoAgentesAD oCesidaMovimientosAgente = new CesidaMovimientoAgentesAD();
        private TurnosWebAD oTurnos = new TurnosWebAD();

        private BDEntities db = new BDEntities();

        #region Results

        public JsonResult login(string device_id, int legajo)
        {
            return this.Json(oAgentesRN.validarApp(device_id, legajo), JsonRequestBehavior.AllowGet);
        }

        //public JsonResult testMovimiento() {

        //   Service.post<>


        //}

        public JsonResult deviceEnabled(string device_id)
        {

            var res = new Result();

            if (this.oAgentesRN.deviceEnabled(device_id))
            {
                res.state = true;
                res.message = "Dispositivo habilitado";
                res.exception = "";
            }
            else
            {
                res.state = false;
                res.message = "Dispositivo deshabilitado";
                res.exception = "El dispositivo " + device_id + " no está habilitado";
            }

            return this.Json(res, JsonRequestBehavior.AllowGet);

        }

        #endregion

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IndexSueldos()
        {
            return View();
        }

        public ActionResult IndexBonificaciones()
        {
            return View();
        }

        public ActionResult Bonificaciones()
        {
            return View();
        }

        public ActionResult Default()
        {
            return View();
        }

        public ActionResult CrearCertificado()
        {
            return View();
        }

        public ActionResult TurnosWeb()
        {
            return View();
        }

        public ActionResult ArchivosAdjuntos(int id)
        {
            ViewBag.Id = id;
            return View(id);
        }

        public ActionResult Proveedores()
        {
            return View();
        }

        public ActionResult TurnosWebDetalle(int id)
        {
            var turno = oTurnos.ObtenerPorId(id);

            return View(turno);
        }

        public ActionResult ProveedoresDetalle(int id)
        {
            var oProveedores = new ECO_ProveedoresAD();
            var proveedor = oProveedores.ObtenerPorId(id);

            return View(proveedor);
        }
        public ActionResult HistorialAdjuntos(int id)
        {
            var oProveedorAdjuntos= new ECO_ProveedoresAdjuntosAD();
            var adjuntos = oProveedorAdjuntos.ObtenerHistorialAdjuntos(id);
            return View(adjuntos);
        }


        public ActionResult MinisterioPublico()
        {
            return View();
        }

        public ActionResult Resumen(int agente)
        {
            Agentes a = oAgentesRN.ObtenerPorId(agente);
            var dias = oAgentesRN.DiasDeLicenciaDisponiblesSustitutos(agente, DateTime.Now);
            ViewBag.DiasSustituto = dias;

            //ViewBag.DiasDeLicenciasDisponibles = oAgentesRN.DiasDeLicenciasDisponibles(agente, DateTime.Now.Year);
            return View(a);
        }

        public ActionResult MisDatos()
        {
            var ag = oAgentes.GetByUser(SessionHelper.NombrePersona);

            Agentes a = oAgentesRN.ObtenerPorId(ag.Id);
            ViewBag.Suplente = a.Nombramientos.Where(x => !x.FechaDeBaja.HasValue && !x.FechaEliminacion.HasValue).FirstOrDefault().Cargos.Grupo;
            var dias = oAgentesRN.DiasDeLicenciaDisponiblesSustitutos(ag.Id, DateTime.Now);
            ViewBag.DiasSustituto = dias;

            //ViewBag.DiasDeLicenciasDisponibles = oAgentesRN.DiasDeLicenciasDisponibles(agente, DateTime.Now.Year);
            return View(a);
        }

        public ActionResult CrearMovimientoCesida(int agente)
        {
            Agentes a = oAgentesRN.ObtenerPorId(agente);

            return View(a);
        }

        private DocumentFormat.OpenXml.Wordprocessing.TableCell createTcHeader(string texto) {
            // Create a cell.
            DocumentFormat.OpenXml.Wordprocessing.TableCell tc1 = new DocumentFormat.OpenXml.Wordprocessing.TableCell();


            var paragraph = new DocumentFormat.OpenXml.Wordprocessing.Paragraph();
            var run = new DocumentFormat.OpenXml.Wordprocessing.Run();
            var text = new DocumentFormat.OpenXml.Wordprocessing.Text(texto);
            // your old code for reference:  tc.Append(new DocumentFormat.OpenXml.Wordprocessing.Paragraph(new DocumentFormat.OpenXml.Wordprocessing.Run(new DocumentFormat.OpenXml.Wordprocessing.Text(data[i, j]))));

            RunProperties runProperties1 = new RunProperties();
            DocumentFormat.OpenXml.Wordprocessing.FontSize fontSize1 = new DocumentFormat.OpenXml.Wordprocessing.FontSize() { Val = "24" };
            Bold bold1 = new Bold();
            runProperties1.Append(fontSize1);
            runProperties1.Append(bold1);

            run.Append(runProperties1);
            run.Append(text);

            paragraph.Append(run);
           
            // Specify the width property of the table cell.
            tc1.Append(new TableCellProperties(
                new TableCellWidth() { Type = TableWidthUnitValues.Dxa, Width = "2400" }));


            tc1.Append(paragraph);
            // Specify the table cell content.
            //tc1.Append(new Paragraph(new Run(new Text(text))));

            return tc1;
        }

        private DocumentFormat.OpenXml.Wordprocessing.TableCell createTcData(string texto)
        {
            // Create a cell.
            DocumentFormat.OpenXml.Wordprocessing.TableCell tc1 = new DocumentFormat.OpenXml.Wordprocessing.TableCell();

            // Specify the width property of the table cell.
            tc1.Append(new TableCellProperties(
                new TableCellWidth() { Type = TableWidthUnitValues.Dxa, Width = "2400" }));


            var paragraph = new DocumentFormat.OpenXml.Wordprocessing.Paragraph();
            var run = new DocumentFormat.OpenXml.Wordprocessing.Run();
            var text = new DocumentFormat.OpenXml.Wordprocessing.Text(texto);
            // your old code for reference:  tc.Append(new DocumentFormat.OpenXml.Wordprocessing.Paragraph(new DocumentFormat.OpenXml.Wordprocessing.Run(new DocumentFormat.OpenXml.Wordprocessing.Text(data[i, j]))));

            RunProperties runProperties1 = new RunProperties();
            DocumentFormat.OpenXml.Wordprocessing.FontSize fontSize1 = new DocumentFormat.OpenXml.Wordprocessing.FontSize() { Val = "24" };
            
            runProperties1.Append(fontSize1);

            run.Append(runProperties1);
            run.Append(text);

            paragraph.Append(run);

            // Specify the width property of the table cell.
            tc1.Append(new TableCellProperties(
                new TableCellWidth() { Type = TableWidthUnitValues.Dxa, Width = "2400" }));


            tc1.Append(paragraph);

            // Specify the table cell content.
            //tc1.Append(new Paragraph(new Run(new Text(text))));

            return tc1;
        }

        private DocumentFormat.OpenXml.Wordprocessing.Table createTableMovimientos(Nombramientos n)
        {
            // Create an empty table.
            DocumentFormat.OpenXml.Wordprocessing.Table table = new DocumentFormat.OpenXml.Wordprocessing.Table();

            // Create a TableProperties object and specify its border information.
            TableProperties tblProp = new TableProperties(
                new TableBorders(
                    new TopBorder()
                    {
                        Val =
                        new EnumValue<BorderValues>(BorderValues.Thick),
                        Size = 10
                    },
                    new BottomBorder()
                    {
                        Val =
                        new EnumValue<BorderValues>(BorderValues.Thick),
                        Size = 10
                    },
                    new LeftBorder()
                    {
                        Val =
                        new EnumValue<BorderValues>(BorderValues.Thick),
                        Size = 10
                    },
                    new RightBorder()
                    {
                        Val =

Web/SSO.SGP.Web/Areas/RRHH/Views/Agentes/Default.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Controllers;	


@{
    Layout = null;
}

<!-- SCRIPTS & CSS -->
<script src="Areas/RRHH/ts/Agentes/AgentesManager.js"></script>
<script src="ts/ArchivosAdjuntos/ArchivosAdjuntosManager.js"></script> 
<style>
    #tabs li .ui-icon-close {
        float: left;
        margin: 0.4em 0.2em;
        cursor: pointer;
    }
</style>
<div class="container-fluid">
    <div id="tabs" class="tabbable tabbable-custom ui-tabs ui-widget ui-widget-content ui-corner-all">
        <ul class="nav nav-tabs ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all" id="ul">
        </ul>
    </div>
</div>

<script type="text/javascript">
   var oAgentes = new Agentes.ts.AgentesManager();
   var oArchivosAdjuntos = new ArchivosAdjuntos.ts.ArchivosAdjuntosManager();

    $(function () {
        app.inicializarTab();
    });    
   
</script>

Web/SSO.SGP.Web/Areas/RRHH/Views/Agentes/Detalle.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Controllers;	
@using Syncrosoft.Framework.Controles.MVC;
@model SSO.SGP.EntidadesDeNegocio.Agentes

@{
	Layout = null;
	var hash = "form"+Session.GetHashCode();
}

	
@Scripts.Render("~/bundles/jqueryval")
<script src="ts/Agentes/Detalle.js"></script>
<script src="ts/Agentes/AgentesManager.js"></script>
<script src="ts/Syncro/SyncroModal.js"></script>
@using (Html.BeginForm("Detalle", "Agentes", FormMethod.Post, new { id = hash })) {
<div class="container-fluid">

		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.Legajo, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.Legajo, new {@class = "form-control col-md-12", @id="Legajo"+hash, @tabindex="2"})
			@Html.ValidationMessageFor(model => model.Legajo)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.Telefono, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.Telefono, new {@class = "form-control col-md-12", @id="Telefono"+hash, @tabindex="3"})
			@Html.ValidationMessageFor(model => model.Telefono)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.Profesion, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.Profesion, new {@class = "form-control col-md-12", @id="Profesion"+hash, @tabindex="4"})
			@Html.ValidationMessageFor(model => model.Profesion)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.EstudiosCursados, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.EstudiosCursados, new {@class = "form-control col-md-12", @id="EstudiosCursados"+hash, @tabindex="5"})
			@Html.ValidationMessageFor(model => model.EstudiosCursados)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.AfiliadoISS, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.AfiliadoISS, new {@class = "form-control col-md-12", @id="AfiliadoISS"+hash, @tabindex="6"})
			@Html.ValidationMessageFor(model => model.AfiliadoISS)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.FechaDeCasamiento, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.FechaDeCasamiento, new {@class = "form-control col-md-12", @id="FechaDeCasamiento"+hash, @tabindex="7"})
			@Html.ValidationMessageFor(model => model.FechaDeCasamiento)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.Persona, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.Persona, new {@class = "form-control col-md-12", @id="Persona"+hash, @tabindex="8"})
			@Html.ValidationMessageFor(model => model.Persona)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.NumeroPS, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.NumeroPS, new {@class = "form-control col-md-12", @id="NumeroPS"+hash, @tabindex="12"})
			@Html.ValidationMessageFor(model => model.NumeroPS)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.Domicilio, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.Domicilio, new {@class = "form-control col-md-12", @id="Domicilio"+hash, @tabindex="13"})
			@Html.ValidationMessageFor(model => model.Domicilio)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.FechaUltimoAscenso, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.FechaUltimoAscenso, new {@class = "form-control col-md-12", @id="FechaUltimoAscenso"+hash, @tabindex="14"})
			@Html.ValidationMessageFor(model => model.FechaUltimoAscenso)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.UltimoCargo, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.UltimoCargo, new {@class = "form-control col-md-12", @id="UltimoCargo"+hash, @tabindex="15"})
			@Html.ValidationMessageFor(model => model.UltimoCargo)
		</div>
	</div>	



	</div><!--fin de div md-12-->
</div> <!--fin de row -->


		
			  @Html.HiddenFor(model => model.Id, new {@id="Id" + hash})
		

		
			  @Html.HiddenFor(model => model.Activo, new {@id="Activo" + hash})
		

		
			  @Html.HiddenFor(model => model.FechaBaja, new {@id="FechaBaja" + hash})
		

		
			  @Html.HiddenFor(model => model.FechaAlta, new {@id="FechaAlta" + hash})
		



</div> <!--fin de container-fluid-->
}

	<script type="text/javascript">       
		$(function () {
			app.Desbloquear();
		});
		
		if (oAgentes == null)
			var oAgentes = new Agentes.ts.AgentesManager();
		
		var viewDetalle = new Agentes.ts.Detalle("@(hash)");
		oAgentes.setDetalle(viewDetalle); 
		
		
	</script>	

Web/SSO.SGP.Web/Areas/RRHH/Views/Agentes/IndexBonificaciones.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Areas.RRHH.Controllers;
@using SSO.SGP.Web.Controllers;
@using Syncrosoft.Framework.Controles.MVC;
@model SSO.SGP.EntidadesDeNegocio.Agentes

@{
    Layout = null;
    var hash = "form" + Session.GetHashCode();
}


@Scripts.Render("~/bundles/jqueryval")
<script src="Areas/RRHH/ts/Agentes/IndexBonificaciones.js"></script>
<script src="Areas/RRHH/ts/Agentes/AgentesManager.js"></script>
<script src="ts/Syncro/SyncroModal.js"></script>
@using (Html.BeginForm("Index", "Agentes", FormMethod.Post, new { id = hash }))
{
    <div class="container-fluid">

        <div class="row">

            <div class="col-md-12">

                @{ 			
                 ColumnCommand[] operadoresAgentes = new ColumnCommand[2] {

                 new ColumnCommand {
                    display = "editar",
                    function = "oAgentes.editarbonificaciones_dtAgentes()",
                    icon = "../assets/img/icons/16x16/edit.png",
                    iconclass = "edit",
                    tooltip = "Editar este registro"
                 },
                 new ColumnCommand {
                    display = "eliminar",
                    function = "oAgentes.eliminarbonificaciones_dtAgentes()",
                    icon = "../assets/img/icons/16x16/delete.png",
                    iconclass = "delete",
                    tooltip = "Eliminar este registro"
                 }                           
                };

                    var vmAgentes = Html.DataTableVm("dtBonificaciones", (AgentesController h) => h.getBonficacionesGrilla(null));

                    vmAgentes.operators = operadoresAgentes;
                    vmAgentes.OpcionesEnGrilla = false;
                    //vmAgentes.fnDrawCallBack = "render_dtAgentes(this);";
                    vmAgentes.ColumnFilter = true;
                    //vmAgentes.FilterOn("activo").Select("Si", "No");
                    //Cantidad de registros a mostrar
                    vmAgentes.CantidadRegistrosDefault = 25;

                }
                @Html.Partial("~/Views/Shared/DataTable.cshtml", vmAgentes)

                <input type="hidden" id="SelectedAgentes@(hash)" value="" />
            </div>
            <!--fin de div md-12-->
        </div>
        <!--fin de row -->
    </div> <!--fin de container-fluid-->
}

<script type="text/javascript">
    $(function () {
        app.Desbloquear();
    });

    if (oAgentes == null)
        var oAgentes = new Agentes.ts.AgentesManager();

    var viewIndexBonificaciones = new Agentes.ts.IndexBonificaciones("@(hash)");
    oAgentes.setIndexBonificaciones(viewIndexBonificaciones);

    viewIndexBonificaciones.setBonificaciones(dtBonificaciones);

</script>