Web/SSO.SGP.Web/Areas/Expedientes/Controllers/ExpedientesADMController.cs
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SSO.SGP.EntidadesDeNegocio;
using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
using SSO.SGP.ReglasDeNegocio;
using SSO.SGP.EntidadesDeNegocio.Vistas;
using System;
using System.Data;
using Syncrosoft.Framework.Utils.Logs;
using SSO.SGP.AccesoADatos;
using SSO.SGP.EntidadesDeNegocio.Results;
using System.Collections.Generic;

namespace SSO.SGP.Web.Areas.Expedientes.Controllers
{
    public class ExpedientesADMController : Controller
    {
        private ExpedientesadmRN oExpedientesADMRN = new ExpedientesadmRN();
        private CategoriasExpedienteadmRefRN oCategoriasExpedienteADMRefRN = new CategoriasExpedienteadmRefRN();
        private OrganismosRefRN oOrganismosRefRN = new OrganismosRefRN();
        private TiposExpedienteadmRefRN oTiposExpedienteADMRefRN = new TiposExpedienteadmRefRN();
        private UsuariosRN oUsuariosRN = new UsuariosRN();
        private ParametrosadmRN oParametrosRN = new ParametrosadmRN();
        private AmbitosRN oAmbitosRN = new AmbitosRN();
        private ExpedientesadmAD oExpedientesAD = new ExpedientesadmAD();
        private UnidadesDeOrganizacionRefAD oUnidadDeOrganizacion = new UnidadesDeOrganizacionRefAD();
        private ImputacionesContablesAD oImputacions = new ImputacionesContablesAD();
        private ImputacionesContablesDetalleAD oImputacionDetalle = new ImputacionesContablesDetalleAD();
        private FacturasAD oFacturas = new FacturasAD();
        private EjecucionesPresupuestariasAD oEjecucion = new EjecucionesPresupuestariasAD();
        private ActuacionesadmAD oActuaciones = new ActuacionesadmAD();


        public ActionResult Asignar(int expediente)
        {
            var f = oExpedientesAD.ObtenerPorId(expediente);
            ViewBag.UnidadDeOrganizacion = new SelectList(oUnidadDeOrganizacion.ObtenerTodo().ToList(), "Id", "Nombre");
            ViewBag.Numero = f.Numero;
            //ViewBag.Importe = f.Importe;
            ViewBag.Id = expediente;
            return View();
        }

        public ActionResult Sobreafectar(int expediente)
        {
            var f = oExpedientesAD.ObtenerPorId(expediente);
            ViewBag.UnidadDeOrganizacion = new SelectList(oUnidadDeOrganizacion.ObtenerTodo().ToList(), "Id", "Nombre");
            ViewBag.Numero = f.Numero;
            //ViewBag.Importe = f.Importe;
            ViewBag.Id = expediente;
            return View();
        }

        public ActionResult Desafectar(int expediente)
        {
            var f = oExpedientesAD.ObtenerPorId(expediente);
            ViewBag.UnidadDeOrganizacion = new SelectList(oUnidadDeOrganizacion.ObtenerTodo().ToList(), "Id", "Nombre");
            ViewBag.Numero = f.Numero;
            //ViewBag.Importe = f.Importe;
            ViewBag.Id = expediente;
            return View();
        }

        [HttpPost]
        public ActionResult AnularActuacion(int actuacion)
        {
            try
            {
                var x = this.oActuaciones.ObtenerPorId(actuacion);

                if (x.OficinaOrigen == SessionHelper.OficinaActual)
                {

                    x.Anulado = true;
                    x.FechaAnulado = DateTime.Now;
                    x.UsuarioAnulacion = SessionHelper.IdUsuario.Value;

                    oActuaciones.Actualizar(x);

                    return Json(new object[] { true, String.Format("La actuación ha sido anulada") });
                }
                else
                {
                    return Json(new object[] { false, String.Format("La actuación no puede anularse") });
                }
            }
            catch (Exception e)
            {
                return Json(new object[] { false, String.Format("Ocurrió un error al anular la actuación: " + e.Message) });
            }
        }

        [HttpPost]
        public ActionResult Sobreafectar(ImputacionesContables imputacion, bool compromiso_y_ordenado)
        {
            try
            {
                imputacion.Fecha = DateTime.Now;
                imputacion.UsuarioAlta = SessionHelper.IdUsuario.Value;
                imputacion.Operacion = (int)eOperacionesContables.SobreAfectacion;

                foreach (var d in imputacion.ImputacionesContablesDetalle)
                {
                    d.Fecha = DateTime.Now;
                    d.Usuario = SessionHelper.IdUsuario.Value;
                }

                oImputacions.Guardar(imputacion);

                var compromiso = oExpedientesAD.obtenerImputacionCompromiso(imputacion.ExpedienteAImputar).ToList();
                var ordenado = oExpedientesAD.obtenerImputacionOrdenadoAPagar(imputacion.ExpedienteAImputar).ToList();

                if (compromiso_y_ordenado)
                {                   
                    if (compromiso.Count() > 0)
                    {
                        var c = new ImputacionesContables()
                        {
                            ExpedienteAImputar = imputacion.ExpedienteAImputar,
                            UsuarioAlta = SessionHelper.IdUsuario.Value,
                            Operacion = (int)eOperacionesContables.Compromiso,
                            Fecha = DateTime.Now
                        };
                        //c.ImputacionesContablesDetalle = new List<ImputacionesContablesDetalle>();                        
                        oImputacions.Guardar(c);
                        foreach (var d in imputacion.ImputacionesContablesDetalle)
                        {
                            var cd = new ImputacionesContablesDetalle()
                            {
                                Division = d.Division,
                                Importe = (d.Importe > 0 ? d.Importe * (1) : d.Importe),
                                AnioContable = d.AnioContable,
                                Fecha = DateTime.Now,
                                Usuario = SessionHelper.IdUsuario.Value,
                                Partida = d.Partida,
                                ImputacionContable = c.Id
                            };
                            oImputacionDetalle.Guardar(cd);
                        }
                    }

                    if (ordenado.Count() > 0)
                    {
                        var o = new ImputacionesContables()
                        {
                            ExpedienteAImputar = imputacion.ExpedienteAImputar,
                            UsuarioAlta = SessionHelper.IdUsuario.Value,
                            Operacion = (int)eOperacionesContables.OrdenadoAPagar,
                            Fecha = DateTime.Now
                        };
                        //o.ImputacionesContablesDetalle = new List<ImputacionesContablesDetalle>();                        
                        oImputacions.Guardar(o);
                        foreach (var d in imputacion.ImputacionesContablesDetalle)
                        {
                            var od = new ImputacionesContablesDetalle()
                            {
                                Division = d.Division,
                                Importe = (d.Importe > 0 ? d.Importe * (1) : d.Importe),
                                AnioContable = d.AnioContable,
                                Fecha = DateTime.Now,
                                Usuario = SessionHelper.IdUsuario.Value,
                                Partida = d.Partida,
                                ImputacionContable = o.Id
                            };
                            oImputacionDetalle.Guardar(od);
                            //o.ImputacionesContablesDetalle.Add(od);
                        }
                    }
                    
                }

                foreach (var d in imputacion.ImputacionesContablesDetalle)
                {
                    var ejecucion = oEjecucion.ObtenerPorPartidaYAnio(DateTime.Now.Year, d.Partida);
                    ejecucion.MontoPreventiva += d.Importe;
                    ejecucion.CreditoDisponible -= d.Importe;

                    if (compromiso_y_ordenado & compromiso.Count() > 0)
                        ejecucion.MontoCompromiso += d.Importe;

                    if (compromiso_y_ordenado & ordenado.Count() > 0)
                        ejecucion.MontoOrdenadoAPagar += d.Importe;

                    oEjecucion.Actualizar(ejecucion);
                }

                return Json(new object[] { true, String.Format("La sobreafectación se realizó con éxito") });
            }
            catch (Exception e)
            {
                Logger.GrabarExcepcion(e, false);
                return Json(new object[] { false, "No se ha podido guardar la imputación" });
            }

        }

        [HttpPost]
        public ActionResult Desafectar(ImputacionesContables imputacion, bool compromiso_y_ordenado)
        {

            try
            {
                imputacion.Fecha = DateTime.Now;
                imputacion.UsuarioAlta = SessionHelper.IdUsuario.Value;
                imputacion.Operacion = (int)eOperacionesContables.Desafectacion;

                foreach (var d in imputacion.ImputacionesContablesDetalle)
                {
                    d.Importe = d.Importe;
                    d.Fecha = DateTime.Now;
                    d.Usuario = SessionHelper.IdUsuario.Value;
                }

                oImputacions.Guardar(imputacion);

                var compromiso = oExpedientesAD.obtenerImputacionCompromiso(imputacion.ExpedienteAImputar).ToList();
                var ordenado = oExpedientesAD.obtenerImputacionOrdenadoAPagar(imputacion.ExpedienteAImputar).ToList();

                if (compromiso_y_ordenado)
                {                    
                    if (compromiso.Count() > 0)
                    {
                        var c = new ImputacionesContables()
                        {

Web/SSO.SGP.Web/Areas/Expedientes/Views/ExpedientesADM/Archivados.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Areas.Expedientes.Controllers;
@using Syncrosoft.Framework.Controles.MVC;
@model SSO.SGP.EntidadesDeNegocio.Expedientesadm

@{
    Layout = null;
    var hash = "form" + Session.GetHashCode();
}


@Scripts.Render("~/bundles/jqueryval")
<script src="Areas/Expedientes/ts/ExpedientesADM/Index.js"></script>
<script src="Areas/Expedientes/ts/ExpedientesADM/ExpedientesADMManager.js"></script>
<script src="ts/Syncro/SyncroModal.js"></script>
@using (Html.BeginForm("Index", "ExpedientesADM", FormMethod.Post, new { id = hash }))
{
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-12">

                @{ 			
                    ColumnCommand[] operadoresExpedientesADM = new ColumnCommand[1] {

                 //new ColumnCommand {
                 //   display = "Detalle",
                 //   //function = "ExpedientesADMController_editar(this)",
                 //   function = "oExpedientesADM.detalle_dtExpedientesADM()",
                 //   icon = "../assets/img/icons/16x16/edit.png",
                 //   tooltip = "Ver Detalle"
                 //},
                 new ColumnCommand {
                    display = "Editar",
                    //function = "ExpedientesADMController_editar(this)",
                    function = "oExpedientesADM.detalle_dtExpedientesADM()",
                    icon = "../assets/img/icons/16x16/edit.png",
                    tooltip = "Detalle"
                 }
                };

                    var vmExpedientesADM = Html.DataTableVm("dtExpedientesADM", (ExpedientesADMController h) => h.getExpedientesADMGrillaArchivados(null));

                    vmExpedientesADM.operators = operadoresExpedientesADM;
                    //vmExpedientesADM.fnDrawCallBack = "render_dtExpedientesADM(this);";
                    vmExpedientesADM.ColumnFilter = true;
                    //vmExpedientesADM.FilterOn("activo").Select("Si", "No");
                    //Cantidad de registros a mostrar
                    vmExpedientesADM.CantidadRegistrosDefault = 25;

                }
                @Html.Partial("~/Views/Shared/DataTable.cshtml", vmExpedientesADM)


                <script type="text/javascript">
                    function ExpedientesADMController_editar(el) {
                        var id = getData(el, 1);
                        oExpedientesADM.editar_dtExpedientesADM(id);
                    }

                    function ExpedientesADMController_eliminar(el) {
                        var id = getData(el, 1);
                        oExpedientesADM.eliminar_dtExpedientesADM(id);
                    }
                </script>


                <input type="hidden" id="SelectedExpedientesADM@(hash)" value="" />

            </div>
            <!--fin de div md-12-->
        </div>
        <!--fin de row -->




    </div> <!--fin de container-fluid-->
}

<script type="text/javascript">
    $(function () {
        app.Desbloquear();
    });

    if (oExpedientesADM == null)
        var oExpedientesADM = new ExpedientesADM.ts.ExpedientesADMManager();

    var viewIndex = new ExpedientesADM.ts.Index("@(hash)"); 
    oExpedientesADM.setIndex(viewIndex);

    viewIndex.setExpedientesADM(dtExpedientesADM);

    

</script>

Web/SSO.SGP.Web/Areas/Expedientes/Views/ExpedientesADM/Dashboard.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Areas.Expedientes.Controllers;
@using Syncrosoft.Framework.Controles.MVC;
@model List<SSO.SGP.EntidadesDeNegocio.EjecucionesPresupuestarias>

    @{
        Layout = null;
        var hash = "form" + Session.GetHashCode();
    }


    @Scripts.Render("~/bundles/jqueryval")
    @*<script src="Areas/Expedientes/ts/ExpedientesADM/Index.js"></script>
        <script src="Areas/Expedientes/ts/ExpedientesADM/ExpedientesADMManager.js"></script>*@
    <script src="ts/Syncro/SyncroModal.js"></script>
    <script src="~/assets/plugins/amcharts_3.21.13.free/amcharts/amcharts.js"></script>
    <script src="~/assets/plugins/amcharts_3.21.13.free/amcharts/gauge.js"></script>
    <script src="~/assets/plugins/amcharts_3.21.13.free/amcharts/plugins/export/export.js"></script>
    <link href="~/assets/plugins/amcharts_3.21.13.free/amcharts/plugins/export/export.css" rel="stylesheet" />
    <script src="~/assets/plugins/amcharts_3.21.13.free/amcharts/themes/light.js"></script>
    @using (Html.BeginForm("Index", "ExpedientesADM", FormMethod.Post, new { id = hash }))
    {
        <div class="container-fluid">
            @{
                var registros = Model.Count();
                var rows = registros / 4;
                var inicio = 1;
            }
            @for (int i = 1; i <= rows; i++)
            {
                var t = 0;
                <div class="row">
                    @for (int j = inicio; j <= registros; j++)
                    {
                        if (t == 4)
                        {
                            break;
                        }
                        else
                        {
                            <div class="col-md-3" id="chartdiv@(inicio)" style="height:270px">
                            </div>
                            t++;
                            inicio++;
                        }
                    }
                </div>
            }
        </div> <!--fin de container-fluid-->
                }

    <script type="text/javascript">

        $(function () {
            app.Desbloquear();

        });

        @for (int i = 0; i < Model.Count(); i++) {
            <text>
        var chart@(i) = AmCharts.makeChart("chartdiv@(i)", {
            "theme": "light",
            "type": "gauge",
            "axes": [{
                "topTextFontSize": 20,
                "topTextYOffset": 70,
                "axisColor": "#31d6ea",
                "axisThickness": 1,
                "endValue": @Model[i].Presupuestado.ToString().Replace(",","."),
                "gridInside": true,
                "inside": true,
                "radius": "50%",
                "valueInterval": @Model[i].Presupuestado.ToString().Replace(",", "."),
                "tickColor": "#67b7dc",
                "startAngle": -90,
                "endAngle": 90,
                "unit": "$",
                "bandOutlineAlpha": 0,
                "bands": [{
                    "color": "#0080ff",
                    "endValue": @Model[i].Presupuestado.ToString().Replace(",","."),
                    "innerRadius": "105%",
                    "radius": "170%",
                    "gradientRatio": [0.5, 0, -0.5],
                    "startValue": 0
                }, {
                    "color": "#3cd3a3",
                    "endValue": @(Model[i].CreditoDisponible.ToString().Replace(",", ".")),
                    "balloonText" : "$ " + @(Model[i].CreditoDisponible.ToString().Replace(",", ".")),
                    "innerRadius": "105%",
                    "radius": "170%",
                    "gradientRatio": [0.5, 0, -0.5],
                    "startValue": 0
                }]
            }],
            "titles": [
    {
        "text": "@Model[i].PartidaPresupuestarias.NumeroDePartida",
        "size": 15
    }],
            "arrows": [{
                "alpha": 1,
                "innerRadius": "35%",
                "nailRadius": 0,
                "radius": "170%",
                "value":@(Model[i].CreditoDisponible.ToString().Replace(",", ".")),
            }]
        });


        $("a[href='http://www.amcharts.com']").hide();
        </text>

                    }



        //if (oExpedientesADM == null)
        //    var oExpedientesADM = new ExpedientesADM.ts.ExpedientesADMManager();

    </script>

Web/SSO.SGP.Web/Areas/Expedientes/Views/ExpedientesADM/Default.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Controllers;		

@{
    Layout = null;
}

<!-- SCRIPTS & CSS -->
<script src="Areas/Expedientes/ts/ExpedientesADM/ExpedientesADMManager.js"></script>
<style>
    #tabs li .ui-icon-close {
        float: left;
        margin: 0.4em 0.2em;
        cursor: pointer;
    }
</style>
<div class="container-fluid">
    <div id="tabs" class="tabbable tabbable-custom ui-tabs ui-widget ui-widget-content ui-corner-all">
        <ul class="nav nav-tabs ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all" id="ul">
        </ul>
    </div>
</div>

<script type="text/javascript">
   var oExpedientesADM = new ExpedientesADM.ts.ExpedientesADMManager();

    $(function () {
        app.inicializarTab();
    });    
   
</script>

Web/SSO.SGP.Web/Areas/Expedientes/Views/ExpedientesADM/IndexAceptarCargo.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Areas.Expedientes.Controllers;
@using Syncrosoft.Framework.Controles.MVC;
@model SSO.SGP.EntidadesDeNegocio.Expedientesadm

@{
    Layout = null;
    var hash = "form" + Session.GetHashCode();
}


@Scripts.Render("~/bundles/jqueryval")
<script src="Areas/Expedientes/ts/ExpedientesADM/IndexAceptarCargo.js"></script>
<script src="Areas/Expedientes/ts/ExpedientesADM/ExpedientesADMManager.js"></script>
<script src="ts/Syncro/SyncroModal.js"></script>
@using (Html.BeginForm("Index", "ExpedientesADM", FormMethod.Post, new { id = hash }))
{
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-12">

                @{ 			
                 ColumnCommand[] operadoresExpedientesADM = new ColumnCommand[1] {
				
                 new ColumnCommand {
                    display = "Detalle",
                    //function = "ExpedientesADMController_editar(this)",
                    function = "oExpedientesADM.detalle_dtExpedientesADM()",
					icon = "../assets/img/icons/16x16/edit.png",
                    tooltip = "Ver Detalle"   
                 }
                };

                var vmExpedientesADM = Html.DataTableVm("dtExpedientesADM", (ExpedientesADMController h) => h.getExpedientesADMGrilla(null));

                vmExpedientesADM.operators = operadoresExpedientesADM;
                //vmExpedientesADM.fnDrawCallBack = "render_dtExpedientesADM(this);";
                vmExpedientesADM.ColumnFilter = true;
                //vmExpedientesADM.FilterOn("activo").Select("Si", "No");
                //Cantidad de registros a mostrar
                vmExpedientesADM.CantidadRegistrosDefault = 25;
                  
                }
                @Html.Partial("~/Views/Shared/DataTable.cshtml", vmExpedientesADM)


                <script type="text/javascript">
                    function ExpedientesADMController_editar(el) {
                        var id = getData(el, 1);
                        oExpedientesADM.editar_dtExpedientesADM(id);
                    }

                    function ExpedientesADMController_eliminar(el) {
                        var id = getData(el, 1);
                        oExpedientesADM.eliminar_dtExpedientesADM(id);
                    }
                </script>


                <input type="hidden" id="SelectedExpedientesADM@(hash)" value="" />

            </div>
            <!--fin de div md-12-->
        </div>
        <!--fin de row -->




    </div> <!--fin de container-fluid-->
}

<script type="text/javascript">
    $(function () {
        app.Desbloquear();
    });

    if (oExpedientesADM == null)
        var oExpedientesADM = new ExpedientesADM.ts.ExpedientesADMManager();

    var viewIndex = new ExpedientesADM.ts.Index("@(hash)"); 
    oExpedientesADM.setIndex(viewIndex);

    viewIndex.setExpedientesADM(dtExpedientesADM);

</script>

Web/SSO.SGP.Web/Areas/Expedientes/Views/ExpedientesADM/IndexConCargo.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Areas.Expedientes.Controllers;
@using Syncrosoft.Framework.Controles.MVC;
@model SSO.SGP.EntidadesDeNegocio.Expedientesadm

@{
    Layout = null;
    var hash = "form" + Session.GetHashCode();
}


@Scripts.Render("~/bundles/jqueryval")
<script src="Areas/Expedientes/ts/ExpedientesADM/IndexConCargo.js"></script>
<script src="Areas/Expedientes/ts/ExpedientesADM/ExpedientesADMManager.js"></script>
<script src="ts/Syncro/SyncroModal.js"></script>
@using (Html.BeginForm("Index", "ExpedientesADM", FormMethod.Post, new { id = hash }))
{
    <div class="container-fluid">

        <div class="row">

            <div class="col-md-12">

                @{
                    ColumnCommand[] operadoresExpedientesADM = new ColumnCommand[2] {

                 new ColumnCommand {
                    display = "Detalle",
                    //function = "ExpedientesADMController_editar(this)",
                    function = "oExpedientesADM.detalle_dtExpedientesConCargoPendiente()",
                    icon = "../assets/img/icons/16x16/edit.png",
                    tooltip = "Ver Detalle"
                 },
                 new ColumnCommand {
                    display = "Aceptar",
                    //function = "ExpedientesADMController_editar(this)",
                    function = "oExpedientesADM.aceptar_dtExpedientesConCargoPendiente()",
                    icon = "../assets/img/icons/16x16/asignar.png",
                    tooltip = "Aceptar cargo"
                 },

                };

                    var vmExpedientesADMOperaciones = Html.DataTableVm("dtExpedientesConCargoPendiente", (ExpedientesADMController h) => h.getExpedientesConCargoPendiente(null));

                    vmExpedientesADMOperaciones.operators = operadoresExpedientesADM;
                    vmExpedientesADM.fnDrawCallBack = "render_dtExpedientesADM(this);";
                    vmExpedientesADMOperaciones.ColumnFilter = true;
                    //vmExpedientesADM.FilterOn("activo").Select("Si", "No");
                    //Cantidad de registros a mostrar
                    vmExpedientesADMOperaciones.CantidadRegistrosDefault = 25;

                }
                @Html.Partial("~/Views/Shared/DataTable.cshtml", vmExpedientesADMOperaciones)


                <script type="text/javascript">
                    function ExpedientesADMController_editar(el) {
                        var id = getData(el, 1);
                        oExpedientesADM.editar_dtExpedientesADM(id);
                    }

                    function ExpedientesADMController_eliminar(el) {
                        var id = getData(el, 1);
                        oExpedientesADM.eliminar_dtExpedientesADM(id);
                    }
                </script>


                <input type="hidden" id="SelectedExpedientesADM@(hash)" value="" />

            </div>
            <!--fin de div md-12-->
        </div>
        <!--fin de row -->




    </div> <!--fin de container-fluid-->

                    }

<script type="text/javascript">
    $(function () {
        app.Desbloquear();
    });

    if (oExpedientesADM == null)
        var oExpedientesADM = new ExpedientesADM.ts.ExpedientesADMManager();

    var viewIndexConCargo = new ExpedientesADM.ts.IndexConCargo("@(hash)");
    oExpedientesADM.setIndexConCargo(viewIndexConCargo);

    viewIndexConCargo.setExpedientesADM(dtExpedientesConCargoPendiente);

</script>

Web/SSO.SGP.Web/Areas/Expedientes/Views/ExpedientesADM/IndexOperaciones.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Areas.Expedientes.Controllers;
@using Syncrosoft.Framework.Controles.MVC;
@model SSO.SGP.EntidadesDeNegocio.Expedientesadm

@{
    Layout = null;
    var hash = "form" + Session.GetHashCode();
}


@Scripts.Render("~/bundles/jqueryval")
<script src="Areas/Expedientes/ts/ExpedientesADM/Index.js"></script>
<script src="Areas/Expedientes/ts/ExpedientesADM/ExpedientesADMManager.js"></script>
<script src="ts/Syncro/SyncroModal.js"></script>
@using (Html.BeginForm("Index", "ExpedientesADM", FormMethod.Post, new { id = hash }))
{
    <div class="container-fluid">

        <div class="row">

            <div class="col-md-12">

                @{ 			
                    ColumnCommand[] operadoresExpedientesADM = new ColumnCommand[2] {

                 new ColumnCommand {
                    display = "Detalle",
                    //function = "ExpedientesADMController_editar(this)",
                    function = "oExpedientesADM.detalle_dtExpedientesADM()",
                    icon = "../assets/img/icons/16x16/edit.png",
                    tooltip = "Ver Detalle"
                 },
                 new ColumnCommand {
                    display = "Asignar",
                    //function = "ExpedientesADMController_editar(this)",
                    function = "oExpedientesADM.asignar_dtExpedientesADM()",
                    icon = "../assets/img/icons/16x16/asignar.png",
                    tooltip = "Asignar"
                 },

                };

                    var vmExpedientesADMOperaciones = Html.DataTableVm("dtExpedientesADM", (ExpedientesADMController h) => h.getExpedientesContablesGrilla(null));

                    vmExpedientesADMOperaciones.operators = operadoresExpedientesADM;
                    //vmExpedientesADM.fnDrawCallBack = "render_dtExpedientesADM(this);";
                    vmExpedientesADMOperaciones.ColumnFilter = true;
                    //vmExpedientesADM.FilterOn("activo").Select("Si", "No");
                    //Cantidad de registros a mostrar
                    vmExpedientesADMOperaciones.CantidadRegistrosDefault = 25;

                }
                @Html.Partial("~/Views/Shared/DataTable.cshtml", vmExpedientesADMOperaciones)


                <script type="text/javascript">
                    function ExpedientesADMController_editar(el) {
                        var id = getData(el, 1);
                        oExpedientesADM.editar_dtExpedientesADM(id);
                    }

                    function ExpedientesADMController_eliminar(el) {
                        var id = getData(el, 1);
                        oExpedientesADM.eliminar_dtExpedientesADM(id);
                    }
                </script>


                <input type="hidden" id="SelectedExpedientesADM@(hash)" value="" />

            </div>
            <!--fin de div md-12-->
        </div>
        <!--fin de row -->




    </div> <!--fin de container-fluid-->
}

<script type="text/javascript">
    $(function () {
        app.Desbloquear();
    });

    if (oExpedientesADM == null)
        var oExpedientesADM = new ExpedientesADM.ts.ExpedientesADMManager();

    var viewIndex = new ExpedientesADM.ts.Index("@(hash)"); 
    oExpedientesADM.setIndex(viewIndex);

    viewIndex.setExpedientesADM(dtExpedientesADM);

</script>