Web/SSO.SGP.Web/Areas/RRHH/Controllers/FeriasRefController.cs
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SSO.SGP.EntidadesDeNegocio;
using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
using SSO.SGP.ReglasDeNegocio;
using SSO.SGP.EntidadesDeNegocio.Vistas;
using System;
using System.Data;
using Syncrosoft.Framework.Utils.Logs;

namespace SSO.SGP.Web.Areas.RRHH.Controllers
{
	public class FeriasRefController : Controller
	{
        private FeriasRefRN oFeriasRefRN = new FeriasRefRN();
		public ActionResult Index()
        {
            return View();
        }

		public ActionResult Default() 
		{
			return View();
		}

        public DataTablesResult<FeriasRefView> getFeriasRefGrilla(DataTablesParam dataTableParam)
        {
            return DataTablesResult.Create(this.oFeriasRefRN.ObtenerParaGrilla(), dataTableParam, a => new FeriasRefView()
            {	
			Id=a.Id,	
			Descripcion=a.Descripcion,	
			FechaDesde=a.FechaDesde,	
			FechaHasta=a.FechaHasta,	
			Anio=a.Anio,	
			Paso1=a.Paso1,	
			Paso2=a.Paso2,});
        }

		public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Crear(FeriasRef feriasref)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    feriasref.DiaDesde = feriasref.FechaDesde.Day;
                    feriasref.DiaHasta = feriasref.FechaHasta.Day;
                    feriasref.MesDesde = feriasref.FechaDesde.Month;
                    feriasref.MesHasta = feriasref.FechaHasta.Month;
                    feriasref.Anio = feriasref.FechaDesde.Year;
                    feriasref.Paso1 = false;
                    feriasref.Paso2 = false;
                    oFeriasRefRN.Guardar(feriasref);
                    return Json(new object[] { true, String.Format("Se guardo FeriasRef satisfactoriamente") });
                }
                catch (Exception ex)
				{
					Logger.GrabarExcepcion(ex, false);
                    return Json(new object[] { false, "No se ha podido guardar FeriasRef" });
                }
            }
            else
            {
                return Json(new object[] { false, "No se ha podido guardar FeriasRef" });
            }
        }
	
	
		[HttpPost]
        public ActionResult Editar(FeriasRef feriasref)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    oFeriasRefRN.Actualizar(feriasref);
                    return Json(new object[] { true, String.Format("Se guardo satisfactoriamente FeriasRef") });
                }
                catch (Exception ex)
				{
					Logger.GrabarExcepcion(ex, false);
                    return Json(new object[] { false, "No pudo guardarse FeriasRef" });
                }
            }
            else
            {
                return Json(new object[] { false, "No pudo guardarse FeriasRef" });
            }

        }

        public ActionResult Editar(int id = 0)
        {
			
		
            FeriasRef feriasref = oFeriasRefRN.ObtenerPorId(id);
            if (feriasref == null)
            {
                return HttpNotFound();
            }
            return View(feriasref);
        }

        [HttpPost]
        public ActionResult AsignarJuzgadosDePag(int id)
        {

            try
            {
                int feriasref = oFeriasRefRN.AsignacionDeFeriaJuzgadosDePaz(id);
                return Json(new object[] { true, "Se registraron " + feriasref.ToString() + " agentes a la feria." });
            }
            catch (Exception e) {
                return Json(new object[] { false, "No se pudo registrar la feria a Juzgados de Paz" });
            }
       
        }
	

        [HttpPost, ActionName("Eliminar")]
        public ActionResult EliminarConfirmado(int id)
        {
            try
            {
                oFeriasRefRN.Eliminar(id);
                return Json(new 	object[] { true, "La operación se realizó satisfactoriamente" });
            }
            catch (Exception ex)
			{
				Logger.GrabarExcepcion(ex, false);
                return Json(new object[] { false, "No pudo eliminarse el feriasref" });
            }
        }
		
		public JsonResult JsonT(string term)
        {
            var res = from x in this.oFeriasRefRN.JsonT(term)
                      select x;
            return this.Json(res, JsonRequestBehavior.AllowGet);
        }
		
		//--- Utilizar esta acción para Autocomplete
		public JsonResult JsonOptions(string term)
        {
            var res = from x in this.oFeriasRefRN.ObtenerOptions(term)
                      select x;
            return this.Json(res, JsonRequestBehavior.AllowGet);
        }
		


	protected override void Dispose(bool disposing)
        {
            oFeriasRefRN.Dispose();
			
            base.Dispose(disposing);
        }
	
	} //fin de clase
}

Web/SSO.SGP.Web/Areas/RRHH/Views/FeriasRef/Crear.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Controllers;	
@using SSO.SGP.Web.Areas.RRHH.Controllers;
@using Syncrosoft.Framework.Controles.MVC;
@model SSO.SGP.EntidadesDeNegocio.FeriasRef

@{
	Layout = null;
	var hash = "form"+Session.GetHashCode();
}

<script src="@Url.Content("~/assets/plugins/bootstrap-switch/static/js/bootstrap-switch.min.js")" type="text/javascript"></script>

<link rel="stylesheet" href="@Url.Content("~/assets/plugins/bootstrap-switch/static/stylesheets/bootstrap-switch.min.css")" />	
@Scripts.Render("~/bundles/jqueryval")
<script src="Areas/RRHH/ts/FeriasRef/Crear.js"></script>
<script src="ts/FeriasRef/FeriasRefManager.js"></script>
<script src="ts/Syncro/SyncroModal.js"></script>
@using (Html.BeginForm("Crear", "FeriasRef", FormMethod.Post, new { id = hash })) {
<div class="container-fluid">

		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.Descripcion, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.Descripcion, new {@class = "form-control col-md-12", @id="Descripcion"+hash, @tabindex="1"})
			@Html.ValidationMessageFor(model => model.Descripcion)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.FechaDesde, new { @class= "control-label" })
		<div class="controls">
		<div class="input-append date date-picker" style="position: relative; z-index: 110000;" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
			@Html.TextBoxFor(model => model.FechaDesde, "{0:dd/MM/yyyy}", new {@class="m-wrap form-control m-ctrl-medium date-picker", @id="FechaDesde"+hash, @tabindex="2" })
			<span class="add-on"><i class="icon-calendar"></i></span> 
		</div>
		<script type="text/javascript">
			$(function () {
				$('#FechaDesde@(hash)').datepicker(pickerOpts);
			});
		</script>
		@Html.ValidationMessageFor(model => model.FechaDesde)
		</div>
	</div>


	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="col-md-12">
		
	<div class="control-group">
		@Html.LabelFor(model => model.FechaHasta, new { @class= "control-label" })
		<div class="controls">
		<div class="input-append date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
			@Html.TextBoxFor(model => model.FechaHasta, "{0:dd/MM/yyyy}", new {@class="m-wrap form-control m-ctrl-medium date-picker", @id="FechaHasta"+hash, @tabindex="3" })
			<span class="add-on"><i class="icon-calendar"></i></span> 
		</div>
		<script type="text/javascript">
			$(function () {
				$('#FechaHasta@(hash)').datepicker(pickerOpts);
			});
		</script>
		@Html.ValidationMessageFor(model => model.FechaHasta)
		</div>
	</div>


	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		
	<div class="form-actions">
	
		<input type="button" value="Cancelar" id="Cancelar@(hash)" class="btn" />

		<input type="button" value="Guardar" id="Guardar@(hash)" class="btn green" />

		<input type="button" value="Guardar & Nuevo" id="GuardarYNuevo@(hash)" class="btn blue" />

	</div><!--fin form-actions>-->
</div> <!--fin de container-fluid-->
}

	<script type="text/javascript">       
		$(function () {
			app.Desbloquear();
		});
		
		if (oFeriasRef == null)
			var oFeriasRef = new FeriasRef.ts.FeriasRefManager();
		
		var viewCrear = new FeriasRef.ts.Crear("@(hash)");
		oFeriasRef.setCrear(viewCrear); 
		
		
	</script>	

Web/SSO.SGP.Web/Areas/RRHH/Views/FeriasRef/Default.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Controllers;		

@{
    Layout = null;
}

<!-- SCRIPTS & CSS -->
<script src="Areas/RRHH/ts/FeriasRef/FeriasRefManager.js"></script>
<style>
    #tabs li .ui-icon-close {
        float: left;
        margin: 0.4em 0.2em;
        cursor: pointer;
    }
</style>
<div class="container-fluid">
    <div id="tabs" class="tabbable tabbable-custom ui-tabs ui-widget ui-widget-content ui-corner-all">
        <ul class="nav nav-tabs ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all" id="ul">
        </ul>
    </div>
</div>

<script type="text/javascript">
   var oFeriasRef = new FeriasRef.ts.FeriasRefManager();

    $(function () {
        app.inicializarTab();
    });    
   
</script>

Web/SSO.SGP.Web/Areas/RRHH/Views/FeriasRef/Editar.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Controllers;
@using SSO.SGP.Web.Areas.RRHH.Controllers;
@using Syncrosoft.Framework.Controles.MVC;
@model SSO.SGP.EntidadesDeNegocio.FeriasRef

@{
	Layout = null;
	var hash = "form"+Session.GetHashCode();
}

<script src="@Url.Content("~/assets/plugins/bootstrap-switch/static/js/bootstrap-switch.min.js")" type="text/javascript"></script>

<link rel="stylesheet" href="@Url.Content("~/assets/plugins/bootstrap-switch/static/stylesheets/bootstrap-switch.min.css")" />	
@Scripts.Render("~/bundles/jqueryval")
<script src="Areas/RRHH/ts/FeriasRef/Editar.js"></script>
<script src="Areas/RRHH/ts/FeriasRef/FeriasRefManager.js"></script>
<script src="ts/Syncro/SyncroModal.js"></script>
@using (Html.BeginForm("Editar", "FeriasRef", FormMethod.Post, new { id = hash })) {
<div class="container-fluid">

		<div class="row">
		
		<div class="span12 m-wrap">
		
	<div class="control-group">
		@Html.LabelFor(model => model.Descripcion, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.Descripcion, new {@class = "form-control col-md-12", @id="Descripcion"+hash, @tabindex="2"})
			@Html.ValidationMessageFor(model => model.Descripcion)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="span12 m-wrap">
		
	<div class="control-group">
		@Html.LabelFor(model => model.FechaDesde, new { @class= "control-label" })
		<div class="controls">
		<div class="input-append date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
			@Html.TextBoxFor(model => model.FechaDesde, "{0:dd/MM/yyyy}", new {@class="m-wrap form-control m-ctrl-medium date-picker", @id="FechaDesde"+hash, @tabindex="3" })
			<span class="add-on"><i class="icon-calendar"></i></span> 
		</div>
		<script type="text/javascript">
			$(function () {
				$('#FechaDesde@(hash)').datepicker(pickerOpts);
			});
		</script>
		@Html.ValidationMessageFor(model => model.FechaDesde)
		</div>
	</div>


	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="span12 m-wrap">
		
	<div class="control-group">
		@Html.LabelFor(model => model.FechaHasta, new { @class= "control-label" })
		<div class="controls">
		<div class="input-append date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
			@Html.TextBoxFor(model => model.FechaHasta, "{0:dd/MM/yyyy}", new {@class="m-wrap form-control m-ctrl-medium date-picker", @id="FechaHasta"+hash, @tabindex="4" })
			<span class="add-on"><i class="icon-calendar"></i></span> 
		</div>
		<script type="text/javascript">
			$(function () {
				$('#FechaHasta@(hash)').datepicker(pickerOpts);
			});
		</script>
		@Html.ValidationMessageFor(model => model.FechaHasta)
		</div>
	</div>


	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="span12 m-wrap">
		
	<div class="control-group">
		@Html.LabelFor(model => model.Anio, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.Anio, new {@class = "form-control col-md-12", @id="Anio"+hash, @tabindex="5"})
			@Html.ValidationMessageFor(model => model.Anio)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="span12 m-wrap">
		
	<div class="control-group">
		@Html.LabelFor(model => model.DiaDesde, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.DiaDesde, new {@class = "form-control col-md-12", @id="DiaDesde"+hash, @tabindex="6"})
			@Html.ValidationMessageFor(model => model.DiaDesde)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="span12 m-wrap">
		
	<div class="control-group">
		@Html.LabelFor(model => model.MesDesde, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.MesDesde, new {@class = "form-control col-md-12", @id="MesDesde"+hash, @tabindex="7"})
			@Html.ValidationMessageFor(model => model.MesDesde)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="span12 m-wrap">
		
	<div class="control-group">
		@Html.LabelFor(model => model.DiaHasta, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.DiaHasta, new {@class = "form-control col-md-12", @id="DiaHasta"+hash, @tabindex="8"})
			@Html.ValidationMessageFor(model => model.DiaHasta)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="span12 m-wrap">
		
	<div class="control-group">
		@Html.LabelFor(model => model.MesHasta, new { @class= "control-label" })
		<div class="controls">
			@Html.TextBoxFor(model => model.MesHasta, new {@class = "form-control col-md-12", @id="MesHasta"+hash, @tabindex="9"})
			@Html.ValidationMessageFor(model => model.MesHasta)
		</div>
	</div>	



	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="span12 m-wrap">
		
	<div class="control-group">
		@Html.LabelFor(model => model.Paso1, new { @class= "control-label" })
		<div class="controls">
			@Html.CheckBoxFor(
				m => m.Paso1, 
				new {@id="Paso1"+hash})
			<script type="text/javascript">
				$(function () {
					$('#Paso1@(hash)').bootstrapSwitch();
				});
			</script>
		@Html.ValidationMessageFor(model => model.Paso1)
		</div>
	</div>


	</div><!--fin de div md-12-->
		</div> <!--fin del row-->
		
		<div class="row">
		
		<div class="span12 m-wrap">
		
	<div class="control-group">
		@Html.LabelFor(model => model.Paso2, new { @class= "control-label" })
		<div class="controls">
			@Html.CheckBoxFor(
				m => m.Paso2, 
				new {@id="Paso2"+hash})
			<script type="text/javascript">
				$(function () {
					$('#Paso2@(hash)').bootstrapSwitch();
				});
			</script>
		@Html.ValidationMessageFor(model => model.Paso2)
		</div>
	</div>


	</div><!--fin de div md-12-->
</div> <!--fin de row -->


		
			  @Html.HiddenFor(model => model.Id, new {@id="Id" + hash})
		



	<div class="form-actions">
	
		<input type="button" value="Cancelar" id="Cancelar@(hash)" class="btn" />

		<input type="button" value="Guardar" id="Guardar@(hash)" class="btn green" />

	</div><!--fin form-actions>-->
</div> <!--fin de container-fluid-->
}

	<script type="text/javascript">       
		$(function () {
			app.Desbloquear();
		});
		
		if (oFeriasRef == null)
			var oFeriasRef = new FeriasRef.ts.FeriasRefManager();
		
		var viewEditar = new FeriasRef.ts.Editar("@(hash)");
		oFeriasRef.setEditar(viewEditar); 
		
		
	</script>	