Web/SSO.SGP.Web/Areas/Expedientes/Controllers/VehiculosOficialesRefController.cs
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SSO.SGP.EntidadesDeNegocio;
using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
using SSO.SGP.AccesoADatos;
using SSO.SGP.EntidadesDeNegocio.Vistas;
using System;
using System.Data;
using System.Collections.Generic;
using System.IO;
using Syncrosoft.Framework.Utils.Logs;

/// <summary>
///  CODE GENERATED BY Xeus Technology 
///  Date: 13/12/2018 7:26:38
///  Version: 3
/// <summary>
namespace SSO.SGP.Web.Areas.Expedientes.Controllers
{
	public class VehiculosOficialesRefController : Controller
	{
		private VehiculosOficialesRefAD oVehiculosOficialesRef = new VehiculosOficialesRefAD();

		#region Views

		public ActionResult Default() 
		{
			return View();
		}

		public ActionResult Index() {
            var m = new VehiculosOficialesRef();
			return View(m);
		}
		public ActionResult Crear() {
            var m = new VehiculosOficialesRef();
			return View(m);
		}

		public ActionResult Editar(int id = 0)
        {	
	
VehiculosOficialesRef vehiculosoficialesref = oVehiculosOficialesRef.ObtenerPorId(id);
            if (vehiculosoficialesref == null)
            {
                return HttpNotFound();
            }
            return View(vehiculosoficialesref);
        }

		#endregion

		#region HttpPost

		[HttpPost]
        public ActionResult Crear(VehiculosOficialesRef vehiculosoficialesref)
        {
			if (ModelState.IsValid)
			{
				try
				{
					oVehiculosOficialesRef.Guardar(vehiculosoficialesref);
                    return Json(new object[] { true, String.Format("Operación satisfactoria"), vehiculosoficialesref.Id });
                }
                catch (Exception ex)
                {
					Logger.GrabarExcepcion(ex, false);
                    return Json(new object[] { false, "No se ha podido procesar la operación" });
                }
           }
           else
           {
                return Json(new object[] { false, "Ha ocurrido un error en la validación" });
           }
        }

		[HttpPost]
        public ActionResult Editar(VehiculosOficialesRef vehiculosoficialesref)
        {
            if (ModelState.IsValid)
            {
                try
                {
					
                    oVehiculosOficialesRef.Guardar(vehiculosoficialesref);
                    return Json(new object[] { true, String.Format("Operación satisfactoria") });
                }
                catch (Exception ex)
                {
					Logger.GrabarExcepcion(ex, false);
                    return Json(new object[] { false, "No se ha podido procesar la operación" });
                }
            }
            else
            {
                return Json(new object[] { false, "Ha ocurrido un error en la validació" });
            }
        }

		[HttpPost, ActionName("Eliminar")]
        public ActionResult EliminarConfirmado(int id)
        {
            try
            {
                oVehiculosOficialesRef.Eliminar(id);
				
                return Json(new object[] { true, "La operación se realizó satisfactoriamente" });
            }
            catch (Exception)
            {
                return Json(new object[] { false, "No pudo eliminarse el elementos" });
            }

        }


	    #endregion

	    #region JsonResult

	    public DataTablesResult<VehiculosOficialesRefView> getVehiculosOficialesRefGrid(DataTablesParam dataTableParam)
        {
            return DataTablesResult.Create(this.oVehiculosOficialesRef.ObtenerParaGrilla(), dataTableParam, x => x);
        }

		public JsonResult Options()
        {
            var res = from x in this.oVehiculosOficialesRef.ObtenerOptions("")
                      select x;
            return this.Json(res, JsonRequestBehavior.AllowGet);
        }

		//public JsonResult Table(string term)
  //      {
  //          var res = from x in this.oVehiculosOficialesRef.JsonT(term)
  //                    select x;
  //          return this.Json(res, JsonRequestBehavior.AllowGet);
  //      }

		public JsonResult GetData(int id)
        {            
            return this.Json(this.oVehiculosOficialesRef.ObtenerPorId(id), JsonRequestBehavior.AllowGet);
        }

        //public JsonResult Autocomplete(string term)
        //{
        //    var res = from x in this.oVehiculosOficialesRef.ObtenerAutocomplete(term)
        //              select new { id = x.Id, label = x.Id.ToString() };
        //    return this.Json(res, JsonRequestBehavior.AllowGet);
        //}

        //public JsonResult ExecuteQuery(string where_c, string order_c)
        //{
        //    var res = from x in this.oVehiculosOficialesRef.ExecuteQuery(where_c, order_c,0,0)
        //              select x;
        //    return this.Json(res, JsonRequestBehavior.AllowGet);
        //}

	#endregion

		protected override void Dispose(bool disposing)
        {
			//oVehiculosOficialesRef.Dispose();

			base.Dispose(disposing);
        }


	}
}

Web/SSO.SGP.Web/Areas/Expedientes/Views/VehiculosOficialesRef/Crear.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Areas.Expedientes.Controllers
@using Syncrosoft.Framework.Controles.MVC;
@using SSO.SGP.EntidadesDeNegocio.Vistas;
@model SSO.SGP.EntidadesDeNegocio.VehiculosOficialesRef

<!--
    CODE GENERATED BY Xeus Technology
    Date:  13/12/2018 7:26:38
    Version: 3
-->
@{
    Layout = null;
    var hash = "form" + Session.GetHashCode();
	var value = "";
}
<!-- SCRIPTS -->
<script src="Areas/Expedientes/ts/VehiculosOficialesRef/Crear.js"></script> 
<!-- /SCRIPTS -->
@using (Html.BeginForm("Crear", "VehiculosOficialesRef", FormMethod.Post, new { id = hash }))
{
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">

            <div class="control-group">
                <label class="control-label" for="Legajo">Legajo</label>
                <div class="controls">
                    <input type="text" class="form-control col-md-12" id="Legajo@(hash)" name="Legajo" tabindex="2" value="" />
                </div>
            </div>
        </div>
    </div>
    <!--fin de row-->
    <div class="row">
        <div class="col-md-12">

            <div class="control-group">
                <label class="control-label" for="Patente">Patente</label>
                <div class="controls">
                    <input type="text" class="form-control col-md-12" id="Patente@(hash)" name="Patente" tabindex="3" value="" />
                </div>
            </div>
        </div>
    </div>
    <!--fin de row-->
    <div class="row">
        <div class="col-md-12">

            <div class="control-group">
                <label class="control-label" for="Descripcion">Descripcion</label>
                <div class="controls">
                    <input type="text" class="form-control col-md-12" id="Descripcion@(hash)" name="Descripcion" tabindex="4" value="" />
                </div>
            </div>
        </div>
    </div>


    <div class="form-actions">

        <input type="button" value="Cancelar" id="Cancelar@(hash)" name="Cancelar" class="btn red" />
        <input type="button" value="Guardar" id="Guardar@(hash)" name="Guardar" class="btn green" />
        <input type="button" value="GuardarYNuevo" id="GuardarYNuevo@(hash)" name="GuardarYNuevo" class="btn blue" />
    </div><!--fin form-actions>-->
</div>
}
<script type="text/javascript">
    $(function () {
        app.Desbloquear();
    });
    var viewCrear = new VehiculosOficialesRef.ts.Crear("@(hash)");
    oVehiculosOficialesRef.setCrear(viewCrear);
</script>

Web/SSO.SGP.Web/Areas/Expedientes/Views/VehiculosOficialesRef/Default.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Controllers;		

@{
    Layout = null;
}

<!-- SCRIPTS & CSS -->
<script src="Areas/Expedientes/ts/VehiculosOficialesRef/VehiculosOficialesRefManager.js"></script>
<style>
    #tabs li .ui-icon-close {
        float: left;
        margin: 0.4em 0.2em;
        cursor: pointer;
    }
</style>
<div class="container-fluid">
    <div id="tabs" class="tabbable tabbable-custom ui-tabs ui-widget ui-widget-content ui-corner-all">
        <ul class="nav nav-tabs ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all" id="ul">
        </ul>
    </div>
</div>

<script type="text/javascript">
   var oVehiculosOficialesRef = new VehiculosOficialesRef.ts.VehiculosOficialesRefManager();

    $(function () {
        app.inicializarTab();
    });    
   
</script>

Web/SSO.SGP.Web/Areas/Expedientes/Views/VehiculosOficialesRef/Editar.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Controllers;
@using Syncrosoft.Framework.Controles.MVC;
@using SSO.SGP.EntidadesDeNegocio.Vistas;
@model SSO.SGP.EntidadesDeNegocio.VehiculosOficialesRef

<!--
    CODE GENERATED BY Xeus Technology
    Date:  13/12/2018 7:26:38
    Version: 3    
-->
@{
    Layout = null;
    var hash = "form" + Session.GetHashCode();
	var value = "";
}
<!-- SCRIPTS -->
<!-- <script src="ts/VehiculosOficialesRef/Editar.js"></script> -->
<!-- /SCRIPTS -->

@using (Html.BeginForm("Editar", "VehiculosOficialesRef", FormMethod.Post, new { id = hash }))
{
    <div class="container-fluid">
        <div class="row">
		    <div class="col-md-12">
			
			<div class="control-group">
	<label class="control-label" for="Legajo">Legajo</label>
	<div class="controls">		
		<input type="text" class="form-control col-md-12" id="Legajo@(hash)" name="Legajo" tabindex="2" value="@Model.Legajo")" />
	</div>
</div>				
			</div>            </div>
			<!--fin de row-->
        <div class="row">
		    <div class="col-md-12">
			
			<div class="control-group">
	<label class="control-label" for="Patente">Patente</label>
	<div class="controls">		
		<input type="text" class="form-control col-md-12" id="Patente@(hash)" name="Patente" tabindex="3" value="@Model.Patente")" />
	</div>
</div>				
			</div>            </div>
			<!--fin de row-->
        <div class="row">
		    <div class="col-md-12">
			
			<div class="control-group">
	<label class="control-label" for="Descripcion">Descripcion</label>
	<div class="controls">		
		<input type="text" class="form-control col-md-12" id="Descripcion@(hash)" name="Descripcion" tabindex="4" value="@Model.Descripcion")" />
	</div>
</div>				
			</div>	
	</div>

		<input type="hidden" id="Id@(hash)" name="Id" value="@((Model!=null ) ? ((Model.GetType().GetProperty("Id") != null) ? Model.Id.ToString() : "") : "")" />       

	<div class="form-actions">
	
		<input type="button" value="Cancelar" id="Cancelar@(hash)" name="Cancelar" class="btn red" />	
		<input type="button" value="Guardar" id="Guardar@(hash)" name="Guardar" class="btn green" />	</div><!--fin form-actions>-->
</div>
}
<script type="text/javascript">
    $(function () {
        app.Desbloquear();
    });
	var viewEditar = new VehiculosOficialesRef.ts.Editar("@(hash)");
    oVehiculosOficialesRef.setEditar(viewEditar);
</script>

Web/SSO.SGP.Web/Areas/Expedientes/Views/VehiculosOficialesRef/Index.cshtml
@using Syncrosoft.Framework.Controles.MVC.Script;
@using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
@using SSO.SGP.Web.Areas.Expedientes.Controllers
@using Syncrosoft.Framework.Controles.MVC;
@using SSO.SGP.EntidadesDeNegocio.Vistas;
@model SSO.SGP.EntidadesDeNegocio.VehiculosOficialesRef

<!--
    CODE GENERATED BY Xeus Technology
    Date:  13/12/2018 7:26:38
    Version: 3    
-->
@{
    Layout = null;
    var hash = "form" + Session.GetHashCode();
	var value = "";
}

<script src="Areas/Expedientes/ts/VehiculosOficialesRef/Index.js"></script>
@*
<script src="Areas/Expedientes/ts/MontosDeViaticosManager.js"></script>*@
<script src="ts/Syncro/SyncroModal.js"></script>


@using (Html.BeginForm("Index", "VehiculosOficialesRef", FormMethod.Post, new { id = hash }))
{
    <div class="container-fluid">
        <div class="row">
		    <div class="col-md-12">
			@{ 			
                ColumnCommand[] operadoresVehiculosOficialesRef = new ColumnCommand[2] {
				
                 new ColumnCommand {
                    display = "editar",
                    function = "oVehiculosOficialesRef.editar_dtVehiculosOficialesRef(this)",
                    icon = "../assets/img/icons/16x16/edit.png",
                    tooltip = "Editar este registro"   
                 },
				
                 new ColumnCommand {
                    display = "eliminar",
                    function = "oVehiculosOficialesRef.eliminar_dtVehiculosOficialesRef(this)",
                    icon = "../assets/img/icons/16x16/delete.png",
                    tooltip = "Eliminar este registro"   
                 },
				};
				var vmVehiculosOficialesRef = Html.DataTableVm("dtVehiculosOficialesRef", (VehiculosOficialesRefController h) => h.getVehiculosOficialesRefGrid(null));
                vmVehiculosOficialesRef.operators = operadoresVehiculosOficialesRef;
                vmVehiculosOficialesRef.OpcionesEnGrilla = true;
                //vmVehiculosOficialesRef.fnDrawCallBack = "render_dtVehiculosOficialesRef(this);";
                vmVehiculosOficialesRef.ColumnFilter = true;
                //vmVehiculosOficialesRef.FilterOn("activo").Select("Si", "No");
                vmVehiculosOficialesRef.CantidadRegistrosDefault = 25;
			}
			@Html.Partial("~/Views/Shared/DataTable.cshtml", vmVehiculosOficialesRef)
			<input type="hidden" id="SelectedVehiculosOficialesRef@(hash)" value="" />
			</div>
	
	</div>


	<div class="form-actions">
	</div><!--fin form-actions>-->
</div>
}
<script type="text/javascript">
    $(function () {
        app.Desbloquear();
    });
	var viewIndex = new VehiculosOficialesRef.ts.Index("@(hash)");
    oVehiculosOficialesRef.setIndex(viewIndex);
	viewIndex.setVehiculosOficialesRef(dtVehiculosOficialesRef);
</script>